# Generated by Django 3.1.5 on 2021-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('has_been_played', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(default='', max_length=128)),
                ('scope', models.CharField(max_length=256)),
            ],
        ),
    ]
